Repository leahkemp/pipeface, pull requests merged in 2025-04, with the labels that each got.

#50 Env modules
  config/nextflow_pipeface.config
  config/parameters_pipeface.json
  docs/run_on_nci.md
  pipeface.nf
Labels: enhancement

#51 Jasmine zero genotypes
  pipeface.nf
Labels: enhancement

#52 Drop gnomad/clinvar SV annotation
  config/nextflow_pipeface.config
  docs/database_versions.txt
  pipeface.nf
Labels: enhancement

#54 Add check for 3 sample IDs defined per family
  pipeface.nf
Labels: bug fix

#55 Add info on how to collaboratively code
  README.md
Labels: documentation

#53 Add platform specific settings for jasmine
  pipeface.nf
Labels: enhancement

#56 Read groups
  pipeface.nf
Labels: enhancement

#48 haploid aware mode
  README.md
  config/nextflow_pipeface.config
  config/parameters_pipeface.json
  docs/run_on_nci.md
  pipeface.nf
Labels: enhancement

#57 gvcf and haploid aware mode
  README.md
  config/nextflow_pipeface.config
  config/parameters_pipeface.json
  docs/run_on_nci.md
  pipeface.nf
Labels: enhancement

#58 Release 0.7.0
  README.md
  config/nextflow_pipeface.config
  config/parameters_pipeface.json
  docs/database_versions.txt
  docs/run_on_nci.md
  pipeface.nf
Labels: release

#59 DeepVariant/DeepTrio Update
  config/nextflow_pipeface.config
  pipeface.nf
Labels: enhancement

#60 Tag pipeface version
  pipeface.nf
Labels: enhancement

#61 Update software
  config/nextflow_pipeface.config
  docs/software_versions.txt
Labels: enhancement

#63 Somalier
  README.md
  config/nextflow_pipeface.config
  config/parameters_pipeface.json
  docs/run_on_nci.md
  docs/software_versions.txt
  pipeface.nf
Labels: enhancement

#62 Release 0.8.0
  README.md
  config/nextflow_pipeface.config
  config/parameters_pipeface.json
  docs/run_on_nci.md
  docs/software_versions.txt
  pipeface.nf
Labels: release
